GET http://localhost:3000/users
###
GET http://localhost:3000/users?auth=true
###
GET http://localhost:3000/users/10?auth=true
Accept: application/json
###
POST http://localhost:3000/users?auth=true
Content-Type: application/json

{
  "name": "Иван"
}